### ISSUE TITLE
Connect to other sources

### ISSUE THREAD

**Issue by AlexanderSkjolden65536** [Skatteetaten/terraform-nomad-trino#105]
## Feature description
Connect to other sources/connectors through the module "API"

## Why is it needed?
As of now, this modules seems to only support connecting to minio and hive connectors through the module "API". Connecting to other sources, e.g. postgresql, would be a nice feature and one we would use.

**Comment by fredrikhgrelland** [comment]
@claesgill I believe this should be feasible. Can we prioritise this feature?

**Comment by claesgill** [comment]
> @claesgill I believe this should be feasible. Can we prioritise this feature?

I agree. Will prioritize in the sprint next week.

**Comment by claesgill** [comment]
> > @claesgill I believe this should be feasible. Can we prioritise this feature?
> 
> I agree. Will prioritize in the sprint next week.

We were not able to prioritize this issue this week. Will make a new priorization after easter!
