### ISSUE TITLE
Migrate to trino

### ISSUE THREAD

**Issue by zhenik** [Skatteetaten/terraform-nomad-trino#114]
## What is the issue?
We need to migrate to `trino` in short words.

## Suggestion(s)/solution(s) [Optional]
- using docker image `prestosql` ~> `trino`
  - nomad job
  - ansible scripts (tests)
- fix underlying issues with compatibility
- fix examples

## Checklist (after created issue)
- [X] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by claesgill** [comment]
This is fixed in #109. Pipeline failes atm, but I'll fix this later today.

Note: That Arturo fixed this, but that was not merged to master but to another branch: `presto-to-trino-include-plugin`.

**Comment by claesgill** [comment]
Closing, as it got fixed in #109
