### ISSUE TITLE
"Unexpected end of stream on connection"

### ISSUE THREAD

**Issue by pdmthorsrud** [Skatteetaten/terraform-nomad-trino#93]
## Current behaviour
Fails when verifying tables.
![image](https://user-images.githubusercontent.com/51820995/99779692-bc656000-2b15-11eb-9070-f7ad71f479bf.png)

## Expected behaviour
Successful verification

## How to reproduce?
Run `make up-standalone`

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

**Comment by pdmthorsrud** [comment]
@zhenik could you elaborate on quotes quickly?

**Comment by claesgill** [comment]
I do not have this problem when running `make up-standalone`:
![image](https://user-images.githubusercontent.com/29984156/114661537-79d83600-9cf7-11eb-9cd1-88abf8b3a146.png)


@zhenik Could we close this?

**Comment by zhenik** [comment]
@claesgill jepp.
