### ISSUE TITLE
Presto SQL has been rebranded to Trino

### ISSUE THREAD

**Issue by pdmthorsrud** [Skatteetaten/terraform-nomad-trino#98]
## What is the issue?
Presto SQL was rebranded to trino.io just before the new year.

[why](https://trino.io/blog/2020/12/27/announcing-trino.html)
[docker-image](https://hub.docker.com/r/trinodb/trino)

We need to update the repo to reflect that.

## Suggestion(s)/solution(s) [Optional]
To start, do a full sweep searching for prestosql, and find instances using prestosql docker image and replace with the one above, also change all references in docs from presto to trino

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

**Comment by pdmthorsrud** [comment]
Relevant issue in data-mesh

https://github.com/fredrikhgrelland/data-mesh/pull/119

**Comment by claesgill** [comment]
This got fixed in #107. Closing.
